### ISSUE TITLE
Le métronome2 ne joue qu'une fois les sons sous Firefox

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/metronome2#7]
Le métronome2 ne joue qu'une fois les sons sous Firefox sur mon PC alors qu'il les joue correctement en boucle dans Chrome. Version firefox = 34.0.5

**Comment by pitrackster** [comment]
Peux-tu réessayer ?

**Comment by taniamcnamara** [comment]
Pas mieux. Dans mon dernier test Firefox les seuls sons joués sont les 3 premiers bips de départ, mais pas ceux de la mélodie sélectionnée, alors que c'est OK sous Chrome.

**Comment by taniamcnamara** [comment]
j'ajoute qu'à chaque pause/play, il rejoue 3 bips identiques puis plus rien.

**Comment by pitrackster** [comment]
tu as un moment que je passe voir ce qui se passe sur ton ordi ? 

----- Mail original -----

De: "taniamcnamara" <notifications@github.com> 
À: "InnovaLangues/metronome2" <metronome2@noreply.github.com> 
Cc: "Guillou Patrick" <patrick.guillou@u-grenoble3.fr> 
Envoyé: Mercredi 14 Janvier 2015 12:44:52 
Objet: Re: [metronome2] Le métronome2 ne joue qu'une fois les sons sous Firefox (#7) 



j'ajoute qu'à chaque pause/play, il rejoue 3 bips identiques puis plus rien.

**Comment by pitrackster** [comment]
problème d'url obsolète
